sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_script:
  - npm test | node_modules/.bin/commentator
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
